„PKG_DSM7/scripts/preinst“ ändern

diff --git a/PKG_DSM7/scripts/preinst b/PKG_DSM7/scripts/preinst
--- a/PKG_DSM7/scripts/preinst
+++ b/PKG_DSM7/scripts/preinst
@@ -40,9 +40,12 @@ machinetyp=$(uname --machine)
 device=$( uname -a | awk -F_ '{print $NF}' | sed "s/+/plus/g" )
 
 if [ $machinetyp = "x86_64" ] || [ $machinetyp = "aarch64" ]; then
-    exit 0
-else
     echo "${PKG_NOINSTALL_ERROR_PART1} (${device}) ${PKG_NOINSTALL_ERROR_PART2} ${machinetyp} ${PKG_NOINSTALL_ERROR_PART3}" > $SYNOPKG_TEMP_LOGFILE
+    exit 1
+fi
+
+if [ -a "/var/run/docker.sock" ]; then
+    echo "${PKG_NOINSTALL_MISSING_DOCKER_ERROR}" > $SYNOPKG_TEMP_LOGFILE
     exit 1
 fi
 
